services:
  ollama-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    env_file:
      - ../files/config/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
    volumes:
      - ../files/config:/home/app/config
      - ../files/data:/home/app/data
